CGV/Controllers/FilmController.cs
using Stripe.Checkout;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using DatabaseIO;
using Model;
using CGV.Utils;


namespace CGV.Controllers
{
    /**
     * FilmController
     * 
     * Version 1.0
     * 
     * Date 07-08-2021
     * 
     * Copyright
     * 
     * Modification Logs:
     * DATE            AUTHOR            DESCRIPTION
     * ----------------------------------------------
     * 07-08-2021      NhaNM2              Create
     */
    public class FilmController : Controller
    {
        // GET: Film
        FilmDao filmD = new FilmDao();
        ScheduleDao scheduleD = new ScheduleDao();
        RoomDao roomD = new RoomDao();
        ShowtimeDao showtimeD = new ShowtimeDao();
        BookingDao bookingDao = new BookingDao();
        SeatDao seatD = new SeatDao();
        CommentDao commentD = new CommentDao();
        MailUtils mailUtil = new MailUtils();
        PaymentStripe paymentOnline = new PaymentStripe();
      
        public ActionResult Index()
        {
            return View();
        }

        /**
         * get detail film by id for user
         * @param id
         * @return
         */
        public ActionResult DetailFilm(string id)
        {
            //select film from database by id
            film film = filmD.getDetailFilm(id);
            var listSeat = seatD.getAll();
            if(listSeat != null || film != null) {
                ViewBag.listseat = listSeat;
                return View(film);
            } else {
                ModelState.AddModelError(Constants.Constants.ERROR_SYSTEM, Constants.Constants.ERROR_SYTEM_DETAIL);
            }
            return View(film);
        }

        /**
         * search film by keyseach for user
         * @param keySearch
         * @return
         */
        public ActionResult SearchFilm(string keySearch)
        {
            if (string.IsNullOrEmpty(keySearch)) {
                return RedirectToAction("IndexUser","Home");
            } else {
                //select film from database by key word
                var listSearch = filmD.searchFilm(keySearch);
                ViewBag.keySearch = keySearch;
                var listSeat = seatD.getAll();
                if( listSeat !=null || listSearch != null) {
                    ViewBag.listseat = listSeat;
                    return View(listSearch);
                } else {
                    ModelState.AddModelError(Constants.Constants.ERROR_SYSTEM, Constants.Constants.ERROR_SYTEM_DETAIL);
                }             
                return View(listSearch);
            }      
        }

        /**
         * get schedule by id for user
         * @param id
         * @return
         */
        [HttpPost]
        public  JsonResult  getSchedule(string id)
        {
            //select list schedule by id
             List<schedule> list = scheduleD.getSchedule(id);      
             if (Int32.Parse(id) == 0) {
                  return Json(new { status = Constants.Constants.STATUS_ERROR, msg = Constants.Constants.FILL_OUT_SCHEDULE, JsonRequestBehavior.AllowGet });
             } else {
                  string html = filmD.renderSchedule(list);
                  return Json(new { status = Constants.Constants.STATUS_OK, data = html, msg = Constants.Constants.MSG_SUCCESS, JsonRequestBehavior.AllowGet });
             }    
        }

        /**
         * get showtime by id and idRoom for user
         * @param id
         * @param idRoom
         * @return
         */
        [HttpPost]
        public JsonResult getShowtime(string id,int idRoom)
        {
            List<showtime> listShowtime = null;
            string html = null;
            var idSche = Int32.Parse(id); 
            var scheduledate = scheduleD.getName(idSche);
            string dtnow = DateTime.Today.ToString(Constants.Constants.FORMAT_DATE_STRING);
            int todayd = Int32.Parse(dtnow);
            string dateint = String.Format(Constants.Constants.FORMAT_DATE_SCHEDULE, scheduledate.dateschedule);
            int datesche = Int32.Parse(dateint);
            if (datesche == todayd) {
                listShowtime = showtimeD.getShowtime(id, idRoom);
                html = filmD.renderShowtime(listShowtime);
                return Json(new { status = Constants.Constants.STATUS_OK, data = html, msg = Constants.Constants.MSG_SUCCESS, JsonRequestBehavior.AllowGet });
            } else {
                listShowtime = showtimeD.getShowtimes(id, idRoom);
                html = filmD.renderShowtime(listShowtime);
                return Json(new { status = Constants.Constants.STATUS_OK, data = html, msg = Constants.Constants.MSG_SUCCESS, JsonRequestBehavior.AllowGet });
            }           
        }

        /**
         * get room by id for user
         * @param id
         * @return
         */
        [HttpPost]
        public JsonResult getRoom(int id)
        {
            //select list room from database by id
            List<room> listRoom = roomD.getRoom(id);
            string html = filmD.renderRoom(listRoom);        
            return Json(new { status = Constants.Constants.STATUS_OK, data = html, msg = Constants.Constants.MSG_SUCCESS, JsonRequestBehavior.AllowGet });
        }

        /**
         * get seat by id for user
         * @param id
         * @param showtimeId
         * @param filmId
         * @param scheduleId
         * @return
         */
        [HttpPost]
        public JsonResult getSeat(int roomId, int showtimeId, int filmId, int scheduleId)
        {
            //select list seat done by roomId, showtimeId, filmId, scheduleId
            List<seat> listSeat = seatD.getSeatDone(roomId, showtimeId, filmId, scheduleId);
            //select list seat  by roomId, showtimeId, filmId, scheduleId
            List<seat> listSeatRoom = seatD.getSeatRoom(roomId);
            var listSeatActive = filmD.handleGetSeat(listSeatRoom, listSeat); ;
            string html = filmD.renderSeat(listSeatActive);        
            return Json(new { status = Constants.Constants.STATUS_OK, data = html, msg = Constants.Constants.MSG_SUCCESS, JsonRequestBehavior.AllowGet });
        }


        /**
         * booking ticket for user 
         * @param film_id
         * @param schedule_id
         * @param showtime_id
         * @param room_id
         * @param seat_id
         * @return
         */
        [HttpPost]
        public JsonResult bookingTicket( int film_id,int schedule_id,int showtime_id, int room_id, int[] seat_id )
        {
            var userInfomatiom = (usercgv)Session[Constants.Constants.USER_SESSION];
            if (userInfomatiom == null ) {
                return Json(new { status = Constants.Constants.STATUS_ERROR, msg = Constants.Constants.YOU_NEED_LOGIN, JsonRequestBehavior.AllowGet });
            } else {
                //check if the data has changed
                bool checkExist = bookingDao.checkBooking(film_id,schedule_id,showtime_id,room_id,seat_id);
                //check data showtime is working
                bool checkExistShowtime = showtimeD.checkExistShowtime(showtime_id);
                if (checkExist || !checkExistShowtime) {
                    return Json(new { status = Constants.Constants.STATUS_ERROR_ONE, msg = Constants.Constants.CHANGE_DATABASE, JsonRequestBehavior.AllowGet });
                } else {
                    int amount = 0;
                    var listHis = new List<HistoryBooking>();
                    var listG = new List<String>();
                    int lengthSeat = seat_id.Length;
                    string stringDay = null;
                    HistoryBooking his = null;
                    string dateschedule = null;
                    for (int i = 0; i < lengthSeat; i++) {
                        dateschedule = String.Format(Constants.Constants.FORMAT_DATE, scheduleD.getName(schedule_id).dateschedule);
                        stringDay = showtimeD.getName(showtime_id).start_time + "-" + showtimeD.getName(showtime_id).end_time;
                        amount += Constants.Constants.PRICE_TICKET;
                        his = bookingDao.addHistoryBooking(film_id, i, room_id, seat_id[i], dateschedule, amount, stringDay, 0);
                        listHis.Add(his);
                        listG.Add(seatD.getName(seat_id[i]).seat_name);
                    }
                    DateTime now = DateTime.Now;
                    booking book = bookingDao.newObjectBooking(schedule_id, film_id, room_id, showtime_id, userInfomatiom.id, now.Ticks.ToString());
                    Session.Add(Constants.Constants.DATE_NOW_STRING, now.Ticks.ToString());
                    Session.Add(Constants.Constants.ORDER, book);
                    Session.Add(Constants.Constants.LENGTH_SEAT, seat_id);
                    Session session = paymentOnline.paymentOnline(filmD.getName(film_id).film_name, lengthSeat);
                    return Json(new { status = Constants.Constants.STATUS_OK, data1 = listHis, data2 = listG, data3 = session, msg = Constants.Constants.BOOKINGTICKET_SUCCESS, JsonRequestBehavior.AllowGet });
                }
               
            }        
        }

        /**
         * booking ticket for user 
         * @param film_id
         * @param schedule_id
         * @param showtime_id
         * @param room_id
         * @param seat_id
         * @return
         */
        [HttpPost]
        public JsonResult bookingTicke(int film_id, int schedule_id, int showtime_id, int room_id, int[] seat_id)
        {
            int status = 0;
            int idUserDefault = 1;
            //check if the data has changed
            bool checkExist = bookingDao.checkBooking(film_id, schedule_id, showtime_id, room_id, seat_id);
            //check data showtime is working
            bool checkExistShowtime = showtimeD.checkExistShowtime(showtime_id);
            if (checkExist || !checkExistShowtime) {

CGV/Controllers/ModulesController.cs
using System.Web.Mvc;

namespace CGV.Controllers
{
    /**
     * ModulesController
     * 
     * Version 1.0
     * 
     * Date 07-08-2021
     * 
     * Copyright
     * 
     * Modification Logs:
     * DATE            AUTHOR            DESCRIPTION
     * ----------------------------------------------
     * 07-08-2021      NhaNM2              Create
     */
    public class ModulesController : Controller
    {
        // GET: Modules
        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public ActionResult Header()
        {
            return PartialView();
        }
        [ChildActionOnly]
        public ActionResult Footer()
        {
            return PartialView();
        }
    }
}

CGV/Controllers/PostController.cs
using System.Web.Mvc;
using DatabaseIO;
using Model;

namespace CGV.Controllers
{
    /**
     * PostController
     * 
     * Version 1.0
     * 
     * Date 07-08-2021
     * 
     * Copyright
     * 
     * Modification Logs:
     * DATE            AUTHOR            DESCRIPTION
     * ----------------------------------------------
     * 07-08-2021      NhaNM2              Create
     */
    public class PostController : Controller
    {
        // GET: Post
        PostDao postD = new PostDao();
        public ActionResult Index()
        {
            return View();
        }

        /**
         * get list introduce for user
         * @return
         */
        public ActionResult Promotion()
        {
            var list = postD.getListIntroduce();
            if (list != null) {
                return View(list);
            } else {
                ModelState.AddModelError(Constants.Constants.ERROR_SYSTEM, Constants.Constants.ERROR_SYTEM_DETAIL);
            }
            return View(list);
        }

        /**
         * get detail introduce by id for user
         * @param id
         * @return
         */
        public ActionResult DetailPromotion(string id)
        {
            post post = postD.getDetailPromotion(id);
            if (post != null) {
                return View(post);
            } else {
                ModelState.AddModelError(Constants.Constants.ERROR_SYSTEM, Constants.Constants.ERROR_SYTEM_DETAIL);
            }
            return View(post);
        }
    }
}

CGV/Views/Modules/Footer.cshtml
<div class="footer--info">
    <div class="footer--item">
        <img src="./images/logo.png" alt="" class="footer--logo" />
    </div>
    <div class="footer--item">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15335.564408777373!2d108.2238517!3d16.0711398!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xbb4619d455ec4348!2zUuG6oXAgQ2hp4bq_dSBwaGltIEzDqiDEkOG7mQ!5e0!3m2!1sen!2s!4v1622430693961!5m2!1sen!2s"
                width="300" height="200" style="border: 0" allowfullscreen="" loading="lazy"></iframe>
    </div>
    <div class="footer--item">
        Contact:

        <a href="https://www.facebook.com/">
            <i class="fab fa-facebook-f footer--media"></i>
        </a>
        <a href="https://www.instagram.com/">
            <i class="fab fa-instagram footer--media"></i>
        </a>
        <a href="https://www.youtube.com/">
            <i class="fab fa-youtube footer--media"></i>
        </a>
        <a href="https://www.google.com/">
            <i class="fab fa-google footer--media"></i>
        </a>
    </div>
    <div class="footer--item">
        <div class="footer--support">
            <span style="text-transform: uppercase; color: #d42304">Chăm sóc khách hàng:</span>
            <br />
            <br />
            Hotline: 1900 112 113<br />
            <br />
            Giờ làm việc: 8:00 - 22:00 (Tất cả các ngày bao gồm cả Lễ Tết)<br />
            <br />
            Email hỗ trợ:<span style="color: #d42304"> hoidap@ledo.vn</span>

            <br />

            <span style="color: #d42304">Dang Khoa.author</span>
        </div>
    </div>
</div>

CGV/Views/Modules/Header.cshtml
<nav>
    <!--logo--------------->
    <a href="/Home/Film" class="logo">
        <img src="/Content/Assets/images/logo.png" />
    </a>
    <!--menu--btn----------------->
    <label class="menu-icon" for="menu-btn">
        <span class="nav-icon"></span>
    </label>
    <!--menu-------------->
    @{ 
        var userInfomatiom = (Model.usercgv)Session[CGV.Constants.Constants.USER_SESSION];
        
    }
<ul class="menu">
    <li>@Html.ActionLink("Giới Thiệu", "Promotion", "Post")</li>
    <li>@Html.ActionLink("Phim", "Film", "Home")</li>
    @if (userInfomatiom != null)
    {
        var profile = new DatabaseIO.UserDao().getInformation(userInfomatiom.email);
        <li style="font-size:35px !important">@Html.ActionLink("Lịch sử đặt vé", "HistoryBooking", "Film")</li>
        <li>@Html.ActionLink(profile.username, "ProfileUser", "Home", new { email = @userInfomatiom.email }, null)</li>
        <li>@Html.ActionLink("Đăng Xuất", "Logout", "Authentication")</li>
    }
    else
    {
        <li>@Html.ActionLink("Đăng Nhập", "Login", "Authentication")</li>
        <li>@Html.ActionLink("Đăng Kí", "Register", "Authentication")</li>
    }

</ul>
    <!--search------------->
    @using (Html.BeginForm("SearchFilm", "Film", FormMethod.Get))
    {
        <div class="search" style="width:350px">
            <input type="text" name="keySearch" value="@ViewBag.keySearch" placeholder="Tìm kiếm phim mà bạn yêu thích" />
            <i class="fas fa-search"></i>
        </div>
    }
 
</nav>